Repository hh99-8-13w-8A-final-2/PODO-R-BE, pull requests merged in 2022-09, with the labels that each got.

#17 메인페이지 뮤지컬 리스트 불러오기
  src/main/java/be/podor/musical/controller/MusicalController.java
  src/main/java/be/podor/musical/dto/MusicalListResponseDto.java
  src/main/java/be/podor/musical/service/MusicalService.java
Labels: enhancement

#20 리뷰 작성시 좌석 등급 저장하기
  src/main/java/be/podor/review/dto/ReviewRequestDto.java
  src/main/java/be/podor/review/model/Review.java
  src/main/java/be/podor/theater/dto/ConvenienceResponseDto.java
  src/main/java/be/podor/theater/model/TheaterConvenience.java
  src/main/java/be/podor/theater/model/TheaterSeat.java
  src/main/java/be/podor/theater/model/type/ConvenienceCode.java
  src/main/java/be/podor/theater/model/type/ConvenienceType.java
  src/main/java/be/podor/theater/model/type/FloorType.java
  src/main/java/be/podor/theater/model/type/GradeType.java
  src/main/java/be/podor/theater/repository/TheaterSeatRepository.java
  src/main/java/be/podor/theater/service/TheaterService.java
  src/test/java/be/podor/theater/repository/TheaterSeatRepositoryTest.java
Labels: enhancement

#21 뮤지컬 리뷰 리스트 조회
  src/main/java/be/podor/review/controller/ReviewController.java
  src/main/java/be/podor/review/dto/EvaluationDto.java
  src/main/java/be/podor/review/dto/ReviewDetailResponseDto.java
  src/main/java/be/podor/review/dto/ReviewListResponseDto.java
  src/main/java/be/podor/review/dto/ReviewLiveResponseDto.java
  src/main/java/be/podor/review/model/Review.java
  src/main/java/be/podor/review/model/reviewInfo/Evaluation.java
  src/main/java/be/podor/review/model/reviewInfo/ScoreEnum.java
  src/main/java/be/podor/review/repository/ReviewRepository.java
  src/main/java/be/podor/review/service/ReviewService.java
Labels: enhancement

#24 리뷰 버그 수정
  src/main/java/be/podor/review/dto/ReviewDetailResponseDto.java
  src/main/java/be/podor/review/dto/ReviewListResponseDto.java
  src/main/java/be/podor/review/dto/ReviewLiveResponseDto.java
  src/main/java/be/podor/review/dto/ReviewRequestDto.java
Labels: enhancement

#30 Feture/kakao
  build.gradle
  src/main/java/be/podor/member/controller/KakaoController.java
  src/main/java/be/podor/member/controller/SocialController.java
  src/main/java/be/podor/member/dto/KakaoUserInfoDto.java
  src/main/java/be/podor/member/dto/TwitterUserInfoDto.java
  src/main/java/be/podor/member/model/Member.java
  src/main/java/be/podor/member/repository/MemberRepository.java
  src/main/java/be/podor/member/service/KakaoService.java
  src/main/java/be/podor/member/service/MemberService.java
  src/main/java/be/podor/member/service/TwitterService.java
  src/main/java/be/podor/security/WebSecurityConfig.java
  src/main/java/be/podor/security/jwt/JwtConfiguration.java
  src/main/java/be/podor/security/jwt/JwtFilter.java
  src/main/java/be/podor/security/jwt/JwtTokenProvider.java
  src/main/java/be/podor/security/jwt/TokenDto.java
  src/main/java/be/podor/security/jwt/refresh/RefreshToken.java
  src/main/java/be/podor/security/jwt/refresh/RefreshTokenRepository.java
Labels: feat, refactor

#31 리뷰 태그 버그 수정
  src/main/java/be/podor/review/dto/ReviewListResponseDto.java
  src/main/java/be/podor/review/dto/ReviewRequestDto.java
  src/main/java/be/podor/review/model/Review.java
  src/main/java/be/podor/review/model/tag/Tag.java
  src/main/java/be/podor/review/repository/TagRepository.java
  src/main/java/be/podor/review/service/ReviewService.java
Labels: enhancement

#32 슬랙 웹 훅 추가
  build.gradle
  src/main/java/be/podor/exception/PodorExceptionHandler.java
  src/main/resources/logback-spring.xml
Labels: enhancement

#34 refactor: 라이브리뷰 구성 변경사항 수정
  build.gradle
  src/main/java/be/podor/config/WebSocketConfig.java
  src/main/java/be/podor/review/controller/ReviewController.java
  src/main/java/be/podor/review/dto/ReviewLiveResponseDto.java
  src/main/java/be/podor/review/repository/ReviewRepository.java
  src/main/java/be/podor/review/service/ReviewService.java
  src/main/java/be/podor/theater/model/type/FloorType.java
Labels: refactor

#35 feat: 트위터 로그인
  build.gradle
  src/main/java/be/podor/member/controller/SocialController.java
  src/main/java/be/podor/member/dto/MemberDto.java
  src/main/java/be/podor/member/dto/SocialUserDto.java
  src/main/java/be/podor/member/dto/TwitterUserInfoDto.java
  src/main/java/be/podor/member/model/Member.java
  src/main/java/be/podor/member/repository/MemberRepository.java
  src/main/java/be/podor/member/service/TwitterService.java
  src/main/java/be/podor/security/WebSecurityConfig.java
  src/main/java/be/podor/security/jwt/JwtFilter.java
Labels: feat

#37 feat: 뮤지컬 정보 가져오기
  src/main/java/be/podor/musical/controller/MusicalController.java
  src/main/java/be/podor/musical/dto/MusicalResponseDto.java
  src/main/java/be/podor/musical/model/Musical.java
  src/main/java/be/podor/musical/repository/MusicalRepository.java
  src/main/java/be/podor/musical/service/MusicalService.java
Labels: feat, refactor

#41 feat: 댓글 CRUD
  src/main/java/be/podor/comment/controller/CommentController.java
  src/main/java/be/podor/comment/dto/CommentRequestDto.java
  src/main/java/be/podor/comment/dto/CommentResponseDto.java
  src/main/java/be/podor/comment/model/Comment.java
  src/main/java/be/podor/comment/repository/CommentRepository.java
  src/main/java/be/podor/comment/service/CommentService.java
  src/main/java/be/podor/review/dto/ReviewDetailResponseDto.java
  src/main/java/be/podor/review/dto/ReviewListResponseDto.java
  src/main/java/be/podor/review/model/Review.java
  src/main/java/be/podor/security/jwt/JwtTokenProvider.java
  src/main/java/be/podor/share/LoginUserAuditorAware.java
Labels: feat

#45 feat: 리뷰 수정 삭제
  src/main/java/be/podor/review/controller/ReviewController.java
  src/main/java/be/podor/review/dto/ReviewDetailResponseDto.java
  src/main/java/be/podor/review/model/Review.java
  src/main/java/be/podor/review/repository/ReviewRepository.java
  src/main/java/be/podor/review/service/ReviewService.java
Labels: feat

#46 feat: 인기 뮤지컬 조회
  src/main/java/be/podor/musical/controller/MusicalController.java
  src/main/java/be/podor/musical/model/Musical.java
  src/main/java/be/podor/musical/repository/MusicalRepository.java
  src/main/java/be/podor/musical/service/MusicalService.java
Labels: feat

#47 feat: 리뷰 좋아요
  src/main/java/be/podor/review/dto/ReviewDetailResponseDto.java
  src/main/java/be/podor/review/dto/ReviewListResponseDto.java
  src/main/java/be/podor/review/model/Review.java
  src/main/java/be/podor/reviewheart/controller/ReviewHeartController.java
  src/main/java/be/podor/reviewheart/model/ReviewHeart.java
  src/main/java/be/podor/reviewheart/repository/ReviewHeartRepository.java
  src/main/java/be/podor/reviewheart/service/ReviewHeartService.java
Labels: feat

#48 Feture/kakao
  src/main/java/be/podor/mypage/controller/MyPageController.java
  src/main/java/be/podor/mypage/service/MyPageService.java
  src/main/java/be/podor/review/repository/ReviewRepository.java
  src/main/java/be/podor/security/WebSecurityConfig.java
Labels: feat, refactor

#49 feat: 리뷰 검색
  build.gradle
  src/main/java/be/podor/config/QuerydslConfig.java
  src/main/java/be/podor/review/controller/ReviewController.java
  src/main/java/be/podor/review/dto/ReviewDetailResponseDto.java
  src/main/java/be/podor/review/dto/ReviewListResponseDto.java
  src/main/java/be/podor/review/dto/ReviewLiveResponseDto.java
  src/main/java/be/podor/review/dto/SearchDto.java
  src/main/java/be/podor/review/dto/SearchRequestParam.java
  src/main/java/be/podor/review/model/Review.java
  src/main/java/be/podor/review/model/reviewInfo/Evaluation.java
  src/main/java/be/podor/review/repository/ReviewSearchRepository.java
  src/main/java/be/podor/review/service/ReviewService.java
  src/main/java/be/podor/security/WebSecurityConfig.java
Labels: feat

#50 Feture/mypage
  src/main/java/be/podor/member/model/Member.java
  src/main/java/be/podor/mypage/controller/MyPageController.java
  src/main/java/be/podor/mypage/dto/MyPageRequestDto.java
  src/main/java/be/podor/mypage/dto/MyPageResponseDto.java
  src/main/java/be/podor/mypage/service/MyPageService.java
  src/main/java/be/podor/security/WebSecurityConfig.java
Labels: feat, refactor

#52 refactor: 댓글 조회 페이징
  src/main/java/be/podor/comment/controller/CommentController.java
  src/main/java/be/podor/comment/repository/CommentRepository.java
  src/main/java/be/podor/comment/service/CommentService.java
Labels: feat

#53 feat: 이미지 리사이징
  build.gradle
  src/main/java/be/podor/aws/service/S3Service.java
Labels: feat

#55 feat: 리뷰에 좋아요 개수 추가
  src/main/java/be/podor/mypage/service/MyPageService.java
  src/main/java/be/podor/review/controller/ReviewController.java
  src/main/java/be/podor/review/dto/ReviewDetailResponseDto.java
  src/main/java/be/podor/review/dto/ReviewListResponseDto.java
  src/main/java/be/podor/review/service/ReviewService.java
Labels: feat

#57 refactor: 뮤지컬 관련 정보 추가
  src/main/java/be/podor/musical/dto/MusicalListResponseDto.java
  src/main/java/be/podor/musical/model/Musical.java
  src/main/java/be/podor/musical/service/MusicalService.java
  src/main/java/be/podor/theater/model/type/ConvenienceCode.java
Labels: feat, refactor

#58 feat: 깃헙액션
  .github/workflows/gradle.yml
  .gitignore
  appspec.yml
  build.gradle
  scripts/deploy.sh
  src/main/resources/application-h2.yaml
  src/main/resources/application.yaml
Labels: feat

#59 feat: 태그 조회 기능
  src/main/java/be/podor/review/dto/ReviewDetailResponseDto.java
  src/main/java/be/podor/review/dto/ReviewListResponseDto.java
  src/main/java/be/podor/review/model/tag/ReviewTag.java
  src/main/java/be/podor/review/service/ReviewService.java
  src/main/java/be/podor/security/WebSecurityConfig.java
  src/main/java/be/podor/tag/controller/TagController.java
  src/main/java/be/podor/tag/dto/TagsResponseDto.java
  src/main/java/be/podor/tag/model/Tag.java
  src/main/java/be/podor/tag/repository/TagRepository.java
  src/main/java/be/podor/tag/service/TagService.java
Labels: feat

#65 feat: 이미지 삭제 기능
  src/main/java/be/podor/aws/controller/S3Controller.java
  src/main/java/be/podor/aws/dto/ImageUrlDto.java
  src/main/java/be/podor/aws/service/S3Service.java
Labels: feat

#66 feat 태그 검색 처리
  src/main/java/be/podor/review/dto/SearchDto.java
  src/main/java/be/podor/review/dto/SearchRequestParam.java
  src/main/java/be/podor/review/repository/ReviewRepository.java
  src/main/java/be/podor/review/repository/ReviewSearchRepository.java
  src/main/java/be/podor/review/repository/ReviewTagRepository.java
  src/main/java/be/podor/review/service/ReviewService.java
  src/main/java/be/podor/tag/controller/TagController.java
  src/main/java/be/podor/tag/repository/TagRepository.java
  src/main/java/be/podor/tag/service/TagService.java
Labels: feat, refactor

#68 feat: 리뷰 검색 기능 구현
  src/main/java/be/podor/review/controller/ReviewController.java
  src/main/java/be/podor/review/dto/SearchRequestParam.java
  src/main/java/be/podor/review/dto/search/SearchDto.java
  src/main/java/be/podor/review/dto/search/SearchRequestParam.java
  src/main/java/be/podor/review/repository/ReviewSearchRepository.java
  src/main/java/be/podor/review/service/ReviewService.java
  src/main/java/be/podor/theater/model/type/GradeType.java
Labels: feat

#69 feat: 뮤지컬별 인기 태그 불러오기
  src/main/java/be/podor/PodorApplication.java
  src/main/java/be/podor/review/repository/ReviewTagRepository.java
  src/main/java/be/podor/scheduler/CacheScheduler.java
  src/main/java/be/podor/tag/controller/TagController.java
  src/main/java/be/podor/tag/service/TagService.java
Labels: feat

#71 feat 최근 검색어 [#70]
  src/main/java/be/podor/member/controller/MemberSearchController.java
  src/main/java/be/podor/member/dto/membersearch/MemberSearchRequestDto.java
  src/main/java/be/podor/member/dto/membersearch/MemberSearchResponseDto.java
  src/main/java/be/podor/member/model/MemberSearch.java
  src/main/java/be/podor/member/repository/MemberSearchRepository.java
  src/main/java/be/podor/member/service/MemberSearchService.java
  src/main/java/be/podor/review/service/ReviewService.java
Labels: feat

#74 feat/musical
  src/main/java/be/podor/musical/controller/MusicalController.java
  src/main/java/be/podor/musical/repository/MusicalRepository.java
  src/main/java/be/podor/musical/service/MusicalService.java
  src/main/java/be/podor/security/WebSecurityConfig.java
  src/main/java/be/podor/theater/dto/TheaterResponseDto.java
  src/main/java/be/podor/theater/model/Theater.java
  src/test/java/be/podor/theater/repository/TheaterSeatRepositoryTest.java
Labels: feat

#76 포도알 커스텀 예외처리
  src/main/java/be/podor/aws/service/S3Service.java
  src/main/java/be/podor/comment/controller/CommentController.java
  src/main/java/be/podor/comment/dto/CommentRequestDto.java
  src/main/java/be/podor/comment/service/CommentService.java
  src/main/java/be/podor/exception/PodorExceptionHandler.java
  src/main/java/be/podor/exception/exceptionType/ExceptionType.java
  src/main/java/be/podor/exception/podor/PodoalException.java
  src/main/java/be/podor/member/service/MemberSearchService.java
  src/main/java/be/podor/member/service/MemberService.java
  src/main/java/be/podor/member/validator/MemberValidator.java
  src/main/java/be/podor/musical/service/MusicalService.java
  src/main/java/be/podor/musical/validator/MusicalValidator.java
  src/main/java/be/podor/notice/service/NoticeService.java
  src/main/java/be/podor/notice/validator/NoticeValidator.java
  src/main/java/be/podor/review/dto/ReviewRequestDto.java
  src/main/java/be/podor/review/service/ReviewService.java
  src/main/java/be/podor/review/validator/ReviewValidator.java
  src/main/java/be/podor/reviewheart/service/ReviewHeartService.java
  src/main/java/be/podor/theater/service/TheaterService.java
  src/main/java/be/podor/theater/validator/TheaterSeatValidator.java
  src/main/resources/application.yaml
Labels: feat, refactor
